default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # 以下、3行追加
  username: postgres # 設定したPostgreSQL Accountと同一のもの
  password: password # 設定したPostgreSQL Accountと同一のもの
  host: localhost
development:
  <<: *default
  database: taskleaf_development # appnameのところは、rails new時のappnameになっているはずです。

test:
  <<: *default
  database: taskleaf_test # appnameのところは、rails new時のappnameになっているはずです。